var thebody = d3.select('body')
var themaparea = thebody.append('div')
    .attr("class", "maparea")
    .attr("id", "maparea")
    .style("width", "900")
    .style("border-style", "solid")
    .style("border-width", "1px")
    .style("border-color", "lightblue")
    .style("display", "inline-block")
    .style("position", "relative")

var sliderbox = themaparea.append('div')
    .attr("class", "sliderbox")
    .attr("id", "sliderbox")
    .style("width", "900")
    .style("border-style", "none")
    .style("border-width", "0px")
    .style("display", "inline-block")
    .style("position", "relative")

var mapbox = themaparea.append('div')
    .attr("id", "map")
// .style("width", "1000px")
// .style("height", "500px");